### ISSUE TITLE
Breaksdown doc of everything that needs to be built

### ISSUE THREAD

**Issue by AndrewBarba** [soelgary/CDN#1]
I think we should start making a doc where we can list out all the different pieces of this that need to be built. This will allow us to split the work accordingly. I'm going to be doing the majority (if not all) of my work in Node and I'm guessing you'll be using Java or Python.

**Comment by soelgary** [comment]
I think the http server should be done in node so you can work on that. The DNS server and load balancer would probably be more efficient in something else
